console.log('📖 GUIA RÁPIDO - VERIFICAÇÃO DE DOCUMENTOS');
console.log('='.repeat(70));
console.log('');
console.log('❓ PERGUNTA: Preciso preencher o campo "Documento Original (JSON)"?');
console.log('');
console.log('✅ RESPOSTA: NÃO! O campo JSON é OPCIONAL.');
console.log('');
console.log('─'.repeat(70));
console.log('');
console.log('🎯 COMO VERIFICAR UM DOCUMENTO:');
console.log('');
console.log('📍 MÉTODO 1: Apenas com Código (RECOMENDADO)');
console.log('   1. Abra: http://localhost:3000');
console.log('   2. Digite o código: IL2-9-5C318D90');
console.log('   3. Deixe o campo JSON em BRANCO');
console.log('   4. Clique em "Verificar Documento"');
console.log('   ✅ Pronto! Sistema busca automaticamente na blockchain');
console.log('');
console.log('📍 MÉTODO 2: Com Código + JSON (Opcional)');
console.log('   1. Abra o arquivo: documentos_originais/documento_X.json');
console.log('   2. Copie todo o conteúdo');
console.log('   3. Cole no campo "Documento Original (JSON)"');
console.log('   4. Clique em "Verificar Documento"');
console.log('   ✅ Verifica blockchain E valida o conteúdo!');
console.log('');
console.log('─'.repeat(70));
console.log('');
console.log('📁 SEUS ARQUIVOS ESTÃO EM:');
console.log('');
console.log('   📂 certificados/');
console.log('      └── certificado_9_1763754168113.json  (Certificado completo)');
console.log('');
console.log('   📂 documentos_originais/');
console.log('      └── documento_9_1763754168113.json    (JSON original) 🎯');
console.log('');
console.log('─'.repeat(70));
console.log('');
console.log('💡 DICAS:');
console.log('');
console.log('   ✅ Sempre guarde o código de verificação');
console.log('   ✅ Para verificação rápida: use apenas o código');
console.log('   ✅ Para verificação detalhada: use código + JSON');
console.log('   ✅ O JSON é salvo automaticamente para você!');
console.log('');
console.log('─'.repeat(70));
console.log('');
console.log('🚀 TESTE PRÁTICO:');
console.log('');
console.log('   1. Execute: node teste_arquivos.js');
console.log('   2. Anote o código gerado (ex: IL2-9-5C318D90)');
console.log('   3. Abra: http://localhost:3000');
console.log('   4. Digite APENAS o código');
console.log('   5. Clique em Verificar');
console.log('   ✅ Funciona sem o JSON!');
console.log('');
console.log('='.repeat(70));
console.log('');
console.log('📚 Documentação completa em: COMO_USAR.md');
console.log('');
console.log('✨ Sistema simplificado e pronto para uso!');
console.log('');
